# Generated by Django 5.0.1 on 2024-02-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_budget_expense_delete_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('Travel', 'travel'), ('Electricity', 'electricity'), ('Hotels booking', 'hotel booking'), ('Airtime & Data', 'airtime & data')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Travel', 'travel'), ('Electricity', 'electricity'), ('Hotels booking', 'hotel booking'), ('Airtime & Data', 'airtime & data')], max_length=100),
        ),
    ]
